### PR TITLE
FFMPEG : misc + ffmpeg5 support

### LINKED ISSUE #2752: [Bug]: error when building example programs for dlib (ffmpeg)
### What Operating System(s) are you seeing this problem on?

Linux (x86-64), Linux (aarch64)

### dlib version

git head 

### Python version

_No response_

### Compiler

gcc 11.3

### Expected Behavior

expected all examples to build:
get to around 95% when encountering ffmpeg* programs and then errors out on build.

### Current Behavior

while building the examples for dlib

get the following errors when attempting the new ffmpeg* example programs.

using ubunutu 22.04 with ffmpeg 4.4.2

cat dlib_error

In file included from /home/rfg/w/dlib/dlib/../dlib/media.h:13,
                 from /home/rfg/w/dlib/examples/ffmpeg_webcam_face_pose_ex.cpp:35:
/home/rfg/w/dlib/dlib/../dlib/media/ffmpeg_demuxer.h: In member function ‘bool dlib::ffmpeg::demuxer::open(const dlib::ffmpeg::demuxer::args&)’:
/home/rfg/w/dlib/dlib/../dlib/media/ffmpeg_demuxer.h:657:73: error: invalid conversion from ‘const AVInputFormat*’ to ‘AVInputFormat*’ [-fpermissive]
  657 | AVInputFormat* input_format = st.args_.input_format.empty() ? nullptr : av_find_input_format(st.args_.input_format.c_str());
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             |
      |                                                             const AVInputFormat*

/home/rfg/w/dlib/dlib/../dlib/media/ffmpeg_demuxer.h: In lambda function:
/home/rfg/w/dlib/dlib/../dlib/media/ffmpeg_demuxer.h:695:100: error: invalid conversion from ‘AVCodec**’ to ‘const AVCodec**’ [-fpermissive]
  695 | v_find_best_stream(st.pFormatCtx.get(), media_type, -1, -1, &pCodec, 0);
      |                                                             ^~~~~~~
      |                                                             |
      |                                                             AVCodec**

### Steps to Reproduce

build example programs from dlib/examples

cd dlib/examples; mkdir build; cd build; cmake ..; cmake -build .

### Anything else?

_No response_

### LINKED ISSUE #2753: [Bug]: ffmpeg examples don't build when using cmake 3.8.0, building ffmpeg static libraries from source and installing them in non-global path
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

master

### Python version

_No response_

### Compiler

gcc12

### Expected Behavior

When building ffmpeg from source as static libraries and installing them in non-global path, e.g. /home/pf/ffmpeg_installation, and building the dlib ffmpeg examples using cmake 3.8.0 exactly, it fails.

### Current Behavior

```
ffmpeg_webcam_face_pose_ex.cpp:(.text+0xe58): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text+0xea8): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text+0xed4): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text+0xf69): undefined reference to `av_frame_free'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `main.cold':
ffmpeg_webcam_face_pose_ex.cpp:(.text.unlikely+0xfd0): undefined reference to `av_frame_free'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::details::decoder_extractor::operator=(dlib::ffmpeg::details::decoder_extractor&&) [clone .isra.0]':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractoraSEOS2_.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x117): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractoraSEOS2_.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x149): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractoraSEOS2_.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x19a): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractoraSEOS2_.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x20e): undefined reference to `swr_free'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::details::get_av_error[abi:cxx11](int)':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details12get_av_errorB5cxx11Ei[_ZN4dlib6ffmpeg7details12get_av_errorB5cxx11Ei]+0x6b): undefined reference to `av_strerror'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::frame::frame(int, int, AVPixelFormat, int, int, unsigned long, AVSampleFormat, std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg5frameC2Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE[_ZN4dlib6ffmpeg5frameC5Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE]+0x43): undefined reference to `av_frame_alloc'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg5frameC2Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE[_ZN4dlib6ffmpeg5frameC5Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE]+0x7c): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg5frameC2Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE[_ZN4dlib6ffmpeg5frameC5Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE]+0xcf): undefined reference to `av_frame_get_buffer'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg5frameC2Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE[_ZN4dlib6ffmpeg5frameC5Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE]+0x11e): undefined reference to `av_rescale_q'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg5frameC2Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE[_ZN4dlib6ffmpeg5frameC5Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE]+0x179): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg5frameC2Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE[_ZN4dlib6ffmpeg5frameC5Eii13AVPixelFormatiim14AVSampleFormatNSt6chrono10time_pointINS4_3_V212system_clockENS4_8durationIlSt5ratioILl1ELl1000000000EEEEEE]+0x26a): undefined reference to `av_frame_free'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::frame::copy_from(dlib::ffmpeg::frame const&)':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg5frame9copy_fromERKS1_[_ZN4dlib6ffmpeg5frame9copy_fromERKS1_]+0xe9): undefined reference to `av_frame_copy'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg5frame9copy_fromERKS1_[_ZN4dlib6ffmpeg5frame9copy_fromERKS1_]+0x15a): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg5frame9copy_fromERKS1_[_ZN4dlib6ffmpeg5frame9copy_fromERKS1_]+0x1d2): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg5frame9copy_fromERKS1_[_ZN4dlib6ffmpeg5frame9copy_fromERKS1_]+0x10f): undefined reference to `av_frame_copy_props'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::details::resampler::reset(int, unsigned long, AVSampleFormat, int, unsigned long, AVSampleFormat)':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details9resampler5resetEim14AVSampleFormatimS3_[_ZN4dlib6ffmpeg7details9resampler5resetEim14AVSampleFormatimS3_]+0x88): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details9resampler5resetEim14AVSampleFormatimS3_[_ZN4dlib6ffmpeg7details9resampler5resetEim14AVSampleFormatimS3_]+0xb2): undefined reference to `swr_alloc_set_opts'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details9resampler5resetEim14AVSampleFormatimS3_[_ZN4dlib6ffmpeg7details9resampler5resetEim14AVSampleFormatimS3_]+0xd5): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details9resampler5resetEim14AVSampleFormatimS3_[_ZN4dlib6ffmpeg7details9resampler5resetEim14AVSampleFormatimS3_]+0xde): undefined reference to `swr_init'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details9resampler5resetEim14AVSampleFormatimS3_[_ZN4dlib6ffmpeg7details9resampler5resetEim14AVSampleFormatimS3_]+0x18f): undefined reference to `swr_free'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::details::resizer::resize(dlib::ffmpeg::frame const&, int, int, AVPixelFormat, dlib::ffmpeg::frame&)':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_[_ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_]+0xb1): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_[_ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_]+0xe2): undefined reference to `sws_getContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_[_ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_]+0xf8): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_[_ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_]+0x1cc): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_[_ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_]+0x27a): undefined reference to `sws_scale'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_[_ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_]+0x2b7): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_[_ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_]+0x2e2): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_[_ZN4dlib6ffmpeg7details7resizer6resizeERKNS0_5frameEii13AVPixelFormatRS3_]+0x68f): undefined reference to `av_frame_free'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::details::resampler::resize(dlib::ffmpeg::frame const&, int, unsigned long, AVSampleFormat, dlib::ffmpeg::frame&)':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details9resampler6resizeERKNS0_5frameEim14AVSampleFormatRS3_[_ZN4dlib6ffmpeg7details9resampler6resizeERKNS0_5frameEim14AVSampleFormatRS3_]+0x99): undefined reference to `av_frame_alloc'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details9resampler6resizeERKNS0_5frameEim14AVSampleFormatRS3_[_ZN4dlib6ffmpeg7details9resampler6resizeERKNS0_5frameEim14AVSampleFormatRS3_]+0xd8): undefined reference to `swr_convert_frame'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details9resampler6resizeERKNS0_5frameEim14AVSampleFormatRS3_[_ZN4dlib6ffmpeg7details9resampler6resizeERKNS0_5frameEim14AVSampleFormatRS3_]+0xfe): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details9resampler6resizeERKNS0_5frameEim14AVSampleFormatRS3_[_ZN4dlib6ffmpeg7details9resampler6resizeERKNS0_5frameEim14AVSampleFormatRS3_]+0x12a): undefined reference to `av_rescale_q'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details9resampler6resizeERKNS0_5frameEim14AVSampleFormatRS3_[_ZN4dlib6ffmpeg7details9resampler6resizeERKNS0_5frameEim14AVSampleFormatRS3_]+0x4e0): undefined reference to `av_frame_free'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::details::decoder_extractor::~decoder_extractor()':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorD2Ev[_ZN4dlib6ffmpeg7details17decoder_extractorD5Ev]+0xd6): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorD2Ev[_ZN4dlib6ffmpeg7details17decoder_extractorD5Ev]+0xe7): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorD2Ev[_ZN4dlib6ffmpeg7details17decoder_extractorD5Ev]+0x100): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorD2Ev[_ZN4dlib6ffmpeg7details17decoder_extractorD5Ev]+0x119): undefined reference to `avcodec_free_context'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::demuxer::{unnamed type#1}::~demuxer()':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerUt_D2Ev[_ZN4dlib6ffmpeg7demuxerUt_D5Ev]+0x16f): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerUt_D2Ev[_ZN4dlib6ffmpeg7demuxerUt_D5Ev]+0x180): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerUt_D2Ev[_ZN4dlib6ffmpeg7demuxerUt_D5Ev]+0x199): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerUt_D2Ev[_ZN4dlib6ffmpeg7demuxerUt_D5Ev]+0x1b2): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerUt_D2Ev[_ZN4dlib6ffmpeg7demuxerUt_D5Ev]+0x297): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerUt_D2Ev[_ZN4dlib6ffmpeg7demuxerUt_D5Ev]+0x2a8): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerUt_D2Ev[_ZN4dlib6ffmpeg7demuxerUt_D5Ev]+0x2c1): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerUt_D2Ev[_ZN4dlib6ffmpeg7demuxerUt_D5Ev]+0x2da): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerUt_D2Ev[_ZN4dlib6ffmpeg7demuxerUt_D5Ev]+0x32e): undefined reference to `av_packet_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerUt_D2Ev[_ZN4dlib6ffmpeg7demuxerUt_D5Ev]+0x352): undefined reference to `avformat_close_input'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerUt_D2Ev[_ZN4dlib6ffmpeg7demuxerUt_D5Ev]+0x45c): undefined reference to `avformat_free_context'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `void dlib::ffmpeg::convert<dlib::array2d<dlib::rgb_pixel, dlib::memory_manager_stateless_kernel_1<char> >, true>(dlib::ffmpeg::frame const&, dlib::array2d<dlib::rgb_pixel, dlib::memory_manager_stateless_kernel_1<char> >&)':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7convertINS_7array2dINS_9rgb_pixelENS_33memory_manager_stateless_kernel_1IcEEEELb1EEEvRKNS0_5frameERT_[_ZN4dlib6ffmpeg7convertINS_7array2dINS_9rgb_pixelENS_33memory_manager_stateless_kernel_1IcEEEELb1EEEvRKNS0_5frameERT_]+0xa7): undefined reference to `av_image_get_buffer_size'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7convertINS_7array2dINS_9rgb_pixelENS_33memory_manager_stateless_kernel_1IcEEEELb1EEEvRKNS0_5frameERT_[_ZN4dlib6ffmpeg7convertINS_7array2dINS_9rgb_pixelENS_33memory_manager_stateless_kernel_1IcEEEELb1EEEvRKNS0_5frameERT_]+0x120): undefined reference to `av_image_copy_to_buffer'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::details::decoder_extractor::decoder_extractor(dlib::ffmpeg::details::decoder_extractor::args const&, std::unique_ptr<AVCodecContext, dlib::ffmpeg::details::av_deleter>, AVCodec const*)':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x206): undefined reference to `av_frame_alloc'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x231): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x293): undefined reference to `av_dict_set'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x2e3): undefined reference to `av_strerror'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x40d): undefined reference to `avcodec_open2'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x43f): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x451): undefined reference to `av_dict_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x4c8): undefined reference to `av_strerror'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x6f8): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x709): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x724): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x73f): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractorC2ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec[_ZN4dlib6ffmpeg7details17decoder_extractorC5ERKNS2_4argsESt10unique_ptrI14AVCodecContextNS1_10av_deleterEEPK7AVCodec]+0x77f): undefined reference to `av_dict_free'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::demuxer::open(dlib::ffmpeg::demuxer::args const&)::{lambda(bool)#2}::operator()(bool) const [clone .isra.0]':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x61): undefined reference to `av_find_best_stream'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x97): undefined reference to `avcodec_alloc_context3'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0xcb): undefined reference to `avcodec_parameters_to_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x2d8): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x386): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x3c2): undefined reference to `sws_getContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x3de): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x461): undefined reference to `av_get_pix_fmt_name'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x4d3): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x54a): undefined reference to `av_strerror'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x67c): undefined reference to `av_get_media_type_string'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x852): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0xa39): undefined reference to `av_get_default_channel_layout'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0xaa9): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0xacc): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7demuxer4openERKNS1_4argsEENKUlbE0_clEb.isra.0[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0xbac): undefined reference to `avcodec_free_context'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::details::decoder_extractor::push(std::unique_ptr<AVPacket, dlib::ffmpeg::details::av_deleter> const&)::{lambda(dlib::ffmpeg::details::extract_state&, bool)#2}::operator()(dlib::ffmpeg::details::extract_state&, bool) const':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b[_ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b]+0x3d): undefined reference to `avcodec_receive_frame'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b[_ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b]+0xe2): undefined reference to `av_rescale_q'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b[_ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b]+0x1a3): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b[_ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b]+0x1fa): undefined reference to `av_strerror'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b[_ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b]+0x3b8): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b[_ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b]+0x40d): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b[_ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b]+0x428): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b[_ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b]+0x457): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b[_ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b]+0x47c): undefined reference to `av_rescale_q'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b[_ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b]+0x684): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b[_ZZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEEENKUlRNS1_13extract_stateEbE0_clESA_b]+0x69b): undefined reference to `av_frame_free'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::details::decoder_extractor::push(std::unique_ptr<AVPacket, dlib::ffmpeg::details::av_deleter> const&)':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEE[_ZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEE]+0x86): undefined reference to `avcodec_send_packet'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEE[_ZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEE]+0x159): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEE[_ZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEE]+0x1ae): undefined reference to `av_strerror'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEE[_ZN4dlib6ffmpeg7details17decoder_extractor4pushERKSt10unique_ptrI8AVPacketNS1_10av_deleterEE]+0x2f0): undefined reference to `avcodec_free_context'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::demuxer::fill_queue()':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0xc6): undefined reference to `av_packet_unref'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0xd9): undefined reference to `av_read_frame'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x17a): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x1b8): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x20c): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x320): undefined reference to `avcodec_send_packet'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x3a8): undefined reference to `avcodec_send_packet'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x417): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x450): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x4bf): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x4f8): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x54c): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x5d0): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x623): undefined reference to `av_strerror'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x7b8): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x80b): undefined reference to `av_strerror'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x92e): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x98e): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0x9f0): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0xa20): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0xa7e): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0xbc8): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer10fill_queueEv[_ZN4dlib6ffmpeg7demuxer10fill_queueEv]+0xc09): undefined reference to `av_frame_free'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::demuxer::populate_metadata()':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer17populate_metadataEv[_ZN4dlib6ffmpeg7demuxer17populate_metadataEv]+0x52): undefined reference to `av_dict_get'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer17populate_metadataEv[_ZN4dlib6ffmpeg7demuxer17populate_metadataEv]+0x361): undefined reference to `av_dict_get'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::demuxer::open(dlib::ffmpeg::demuxer::args const&)':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x79e): undefined reference to `avformat_close_input'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x7d5): undefined reference to `av_packet_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x964): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x99b): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x9e7): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0xa67): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0xd2a): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0xd61): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0xdad): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0xe2d): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x12b9): undefined reference to `avformat_alloc_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x152b): undefined reference to `av_dict_set'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x158a): undefined reference to `av_strerror'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x162a): undefined reference to `avformat_open_input'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x1641): undefined reference to `av_dict_count'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x1691): undefined reference to `avformat_close_input'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x16a2): undefined reference to `avformat_find_stream_info'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x16e6): undefined reference to `av_packet_alloc'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x1712): undefined reference to `av_packet_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x1724): undefined reference to `av_dict_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x1795): undefined reference to `av_find_input_format'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x17c0): undefined reference to `avdevice_register_all'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x221c): undefined reference to `avformat_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x22f9): undefined reference to `av_dict_get'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x231c): undefined reference to `avformat_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x27ac): undefined reference to `av_dict_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x289b): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x28ad): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x28cf): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x28f1): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x2990): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x29a2): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x29c4): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxer4openERKNS1_4argsE]+0x29ea): undefined reference to `avcodec_free_context'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `dlib::ffmpeg::demuxer::demuxer(dlib::ffmpeg::demuxer::args const&)':
ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x5d7): undefined reference to `avformat_close_input'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x608): undefined reference to `avformat_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x649): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x65a): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x672): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x68a): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x6be): undefined reference to `swr_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x6cf): undefined reference to `sws_freeContext'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x6e7): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x6ff): undefined reference to `avcodec_free_context'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x73d): undefined reference to `av_packet_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x75c): undefined reference to `avformat_close_input'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text._ZN4dlib6ffmpeg7demuxerC2ERKNS1_4argsE[_ZN4dlib6ffmpeg7demuxerC5ERKNS1_4argsE]+0x778): undefined reference to `avformat_free_context'
/usr/bin/ld: CMakeFiles/ffmpeg_webcam_face_pose_ex.dir/ffmpeg_webcam_face_pose_ex.cpp.o: in function `main':
ffmpeg_webcam_face_pose_ex.cpp:(.text.startup+0x10d6): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text.startup+0x111c): undefined reference to `av_frame_free'
/usr/bin/ld: ffmpeg_webcam_face_pose_ex.cpp:(.text.startup+0x2764): undefined reference to `av_frame_free'

```

### Steps to Reproduce

```
CWD=`pwd`

wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz
tar -xf cmake-3.8.0-Linux-x86_64.tar.gz
CMAKE_PATH=$CWD/cmake-3.8.0-Linux-x86_64/bin/cmake

wget https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n4.4.3.tar.gz
tar -xf n4.4.3.tar.gz
cd FFmpeg-n4.4.3
./configure --prefix=$CWD --disable-doc --disable-programs
make -j`nproc`
make install
cd ..

git clone https://github.com/davisking/dlib.git
cd dlib/examples
mkdir build
cd build
$CMAKE_PATH -DDLIB_USE_CUDA=OFF -DCMAKE_PREFIX_PATH=$CWD ..
make -j`nproc` ffmpeg_webcam_face_pose_ex
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pfeatherstone**
* Enhanced `list_muxers()`
* Added a convenient `fail()` function in the implementation details which helps reduce code
* Moved the `framerate` option in `demuxer::args` to `decoder_image_args`. Makes more sense to have it there
* Refactored `demuxer::args::image_options` to `demuxer::args::args_image` for consistency with `decoder::args`
* Fixes #2752
* ffmpeg5 support
* ffmpeg6 support (no extra work required)
* Fixes #2753

### CODE REVIEW

File: dlib/media/ffmpeg_abstract.h [hunk 1]
```diff
@@ -410,9 +464,12 @@ namespace dlib
 
             // Pixel format of extracted frames. If AV_PIX_FMT_NONE, use whatever comes out decoder. The default is AV_PIX_FMT_RGB24
             AVPixelFormat fmt{AV_PIX_FMT_RGB24};
+
+            // Sets the output framerate for any device that allows you to do so, e.g. webcam, x11grab, etc. Does not apply to files
+            int framerate{-1};
```
Comment (davisking) [inline dlib/media/ffmpeg_abstract.h:469]: What does -1 mean?

**Comment by davisking** [comment]
This all looks good.  Should I merge it or is there something about it that's not ready yet?  I just looked it all over though and aside from that one question about documenting what -1 means looks ready to merge.

File: dlib/media/ffmpeg_abstract.h (hunk 1 above)
Comment (pfeatherstone) [reply dlib/media/ffmpeg_abstract.h:469]: -1 means  not used. I'll add docs

**Comment by pfeatherstone** [comment]
> This all looks good. Should I merge it or is there something about it that's not ready yet? I just looked it all over though and aside from that one question about documenting what -1 means looks ready to merge.

Just added ffmpeg5 support. Sorry, I'm going to squeeze this in. 
I need to edit Github Actions to use ffmpeg5 on one of the jobs.

**Comment by davisking** [comment]
No worries. Let me know when you think it's ready 👍

**Comment by pfeatherstone** [comment]
Last thing to do is add jobs to Github Actions. I suggest:
* Modify one of the existing jobs, install and link against ffmpeg 5
* Add another job that installs a whole bunch of ffmpeg versions and just builds the ffmpeg specific examples. That will run a lot faster, we're not actually executing any code, but we're checking everything compiles without warnings.

**Comment by davisking** [comment]
Yeah I would just modify one of the jobs to link against the other version.  Easy and doesn't make the tests run longer.

File: dlib/media/ffmpeg_utils.h [hunk 2]
```diff
@@ -394,35 +439,188 @@ namespace dlib
...
+
+            inline bool channel_layout_empty(const AVFrame* frame)
+            {
+                return frame && av_channel_layout_check(&frame->ch_layout) == 0;
+            }
+
+            inline uint64_t get_layout(const AVFrame* frame)
+            {
+                return frame->ch_layout.u.mask;
+            }
```
Comment (pfeatherstone) [inline dlib/media/ffmpeg_utils.h:546]: Add overload for `AVCodecContext*`

File: dlib/media/ffmpeg_utils.h [hunk 3]
```diff
@@ -394,35 +439,188 @@ namespace dlib
...
+
+            inline bool channel_layout_empty(const AVFrame* frame)
+            {
+                return frame->channel_layout == 0;
+            }
+
+            inline uint64_t get_layout(const AVFrame* frame)
+            {
+                return frame->channel_layout;
+            }
```
Comment (pfeatherstone) [inline dlib/media/ffmpeg_utils.h:593]: Add overload for `AVCodecContext*`

**Comment by davisking** [comment]
> I might actually have to read the documentations for Github Actions because this copy-paste business isn't working out for me.

Yeah it never works for me like the docs suggest. It's free though so 🤷‍♂️

**Comment by pfeatherstone** [comment]
I don't understand what's going on. Looking at the output of `ubuntu-latest-gcc-default-cmake-3-8-ffmpeg5`, when it comes to linking `dtest` it comes up with a whole bunch of `undefined reference to av_...`. As if the `libavformat.a` etc libraries were empty. I run those exact scripts on 2 different PCs and it works. So no idea what's going on.

**Comment by pfeatherstone** [comment]
> I don't understand what's going on. Looking at the output of `ubuntu-latest-gcc-default-cmake-3-8-ffmpeg5`, when it comes to linking `dtest` it comes up with a whole bunch of `undefined reference to av_...`. As if the `libavformat.a` etc libraries were empty. I run those exact scripts on 2 different PCs and it works. So no idea what's going on.

@arrufat Can you make sense of this?

**Comment by pfeatherstone** [comment]
Also, this happens a lot, the `ubuntu-18_04-gcc-7` job gets cancelled immediately.

**Comment by arrufat** [comment]
I just tried building on my machine (Arch, btw), which has both ffmpeg4 and ffmpeg6.
If I just run CMake normally, it uses ffmpeg6 and the webcam pose ex works well.
If I want to use ffmpeg4, I need to prepend the CMake command with:
`PKG_CONFIG_PATH=/usr/lib/ffmpeg4.4/pkgconfig`. Then it picks up ffmpeg4, and it also works.
It also seems a bit cryptic to me. I'll look into it later… It's time to sleep here.

**Comment by pfeatherstone** [comment]
> I just tried building on my machine (Arch, btw), which has both ffmpeg4 and ffmpeg6. If I just run CMake normally, it uses ffmpeg6 and the webcam pose ex works well. If I want to use ffmpeg4, I need to prepend the CMake command with: `PKG_CONFIG_PATH=/usr/lib/ffmpeg4.4/pkgconfig`. Then it picks up ffmpeg4, and it also works. It also seems a bit cryptic to me. I'll look into it later… It's time to sleep here.

Tried it with cmake 3.8.0 on my machine and I get the error. So it has something to do with cmake 3.8.0 and pkg-config i think

**Comment by pfeatherstone** [comment]
Cmake 3.8.0 is a bit naff to be honest. I think 3.13 should be the required minimum.

File: dlib/CMakeLists.txt [hunk 4]
```diff
@@ -865,8 +869,10 @@ if (NOT TARGET dlib)
       PUBLIC ${dlib_needed_public_includes}
       PRIVATE ${dlib_needed_private_includes}
       )
-   target_link_libraries(dlib PUBLIC ${dlib_needed_public_libraries})
+   target_link_libraries(dlib PUBLIC ${dlib_needed_public_libraries} ${dlib_needed_public_ldflags})
    target_link_libraries(dlib PRIVATE ${dlib_needed_private_libraries})
+   target_compile_options(dlib PUBLIC ${dlib_needed_public_cflags})
+   # target_link_options(dlib PUBLIC ${dlib_needed_public_ldflags})
```
Comment (davisking) [inline dlib/CMakeLists.txt:875]:
```suggestion
```

File: dlib/media/ffmpeg_utils.h [hunk 5]
```diff
@@ -382,6 +410,23 @@ namespace dlib
...
+            template<class... Args>
+            inline bool fail(std::ostream& out, Args&&... args)
+            {
+#ifdef __cpp_fold_expressions
+                ((out << args),...);
+#else
+                (void)std::initializer_list<int>{((out << args), 0)...};
+#endif
+                out << '\n';
+                return false;
```
Comment (davisking) [inline dlib/media/ffmpeg_utils.h:426]: Why return the bool?  It's always `false`.

File: dlib/media/ffmpeg_utils.h [hunk 6]
```diff
@@ -394,33 +439,206 @@ namespace dlib
...
         }
 
-        inline std::string get_pixel_fmt_str(AVPixelFormat fmt)
+// ---------------------------------------------------------------------------------------------------
+
+        ///////////////////////////
+        // Channel layout stuff 
+        ///////////////////////////
+
+        inline uint64_t get_layout_from_channels(const std::size_t nchannels)
```
Comment (davisking) [inline dlib/media/ffmpeg_utils.h:448]: `get_layout_from_channels`, `get_channels_from_layout`, and some of the other stuff below isn't mentioned in the abstract.h docs file.  Should they be?  Seems like these are meant to be hidden implementation details?  Can they be in `details`?

**Review by davisking — COMMENTED** [review]
Looks real nice.

File: dlib/CMakeLists.txt (hunk 4 above)
Comment (pfeatherstone) [reply dlib/CMakeLists.txt:875]: https://cmake.org/cmake/help/latest/command/target_link_options.html
New in version 3.13

File: dlib/media/ffmpeg_utils.h (hunk 5 above)
Comment (pfeatherstone) [reply dlib/media/ffmpeg_utils.h:426]: It's so you can write something like:
```
if (!something_that_can_fail())
    return fail("reason for failing");
```

File: dlib/media/ffmpeg_utils.h (hunk 6 above)
Comment (pfeatherstone) [reply dlib/media/ffmpeg_utils.h:448]: Will check

File: dlib/media/ffmpeg_utils.h (hunk 5 above)
Comment (davisking) [reply dlib/media/ffmpeg_utils.h:426]: Yeah I guess I've come around to this :)

**Comment by davisking** [comment]
Sweet, thanks for the PR :D
